import Head from "next/head";
import WebLogin from "../components/login/WebLogin";
import MobileLogin from "../components/login/MobileLogin";
import { useState } from "react";
import { useRouter } from "next/router";
export default function Home() {
  const [loginObj, setLoginObj] = useState({});
  const router = useRouter();
  const login = async () => {
    const res = await fetch("/api/auth/login", {
      method: "POST",
      body: JSON.stringify(loginObj),
      headers: {
        "content-type": "application/json",
      },
    });
    const data = await res.json();
    localStorage.setItem("token", data?.token);
    router.push("/");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
          width: "100vw",
        }}
      >
        <div className="webView">
          <WebLogin
            loginObj={loginObj}
            setLoginObj={setLoginObj}
            login={login}
          />
        </div>
        <div className="mobileView">
          <MobileLogin
            loginObj={loginObj}
            setLoginObj={setLoginObj}
            login={login}
          />
        </div>
      </main>
    </>
  );
}
