import Head from "next/head";
import WebLogin from "../components/login/WebLogin"
import MobileLogin from "../components/login/MobileLogin";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
          width: "100vw",
        }}
      >
        <div className="webView">
          <WebLogin />
        </div>
        <div className="mobileView">
          <MobileLogin />
        </div>
      </main>
    </>
  );
}
